In [ ]:
# Array attributes and dimensional transformations



# array shape -> shape of the NumPy array tells us number of elements in each dimension(row,column etc)
# It helps us understand structure of the data

import numpy as np

arr = np.array([1,2,3])


print(arr.shape)

(3,)


In [ ]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr.shape)

print(arr)

print(arr.size)



(2, 3)
[[1 2 3]
 [4 5 6]]
6


In [ ]:
arr = np.array([1,2,3])
print(arr.size)   # -> the size of the NumPy array  -> it is the total number of elements in the array

print(arr.ndim)

3
1


In [ ]:
#  ndim -> tells us number of dimensions(axes) of an array

arr= np.array([[1,2,3],[4,5,6]])
print(arr.ndim)

2


In [ ]:
# item size -> this attribute shows the memory size(in bytes) of each elements of the array

arr= np.array([[1,2,3],[4,5,6]])
print(arr.itemsize)

8


In [ ]:
# reshaping of arrays (reshape,ravel,flatten)

# defnitions:
  # reshape() -> returns a new view with a different shape with  out changing the data
  # ravel() -> returns a 1D flattened array (view)    -> usually faster compared to flatten()
  # flatten() -> returns a 1D flattened array(copy )  -> usually slower compared to ravel()



In [ ]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)

print(arr.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr_reshaped = arr.reshape(5,1)

ValueError: cannot reshape array of size 6 into shape (5,1)

In [ ]:
arr_reshaped = arr.reshape(6,1)

In [ ]:
print(arr_reshaped)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [ ]:
arr_reshaped = arr.reshape(3,2)

In [ ]:
print(arr)
print(arr.shape)

print(arr_reshaped)
print(arr_reshaped.shape)


[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [ ]:
# ravel

arr_ravel = arr.ravel()
print(arr_ravel)
print(arr_ravel.shape)

print(arr)
print(arr.shape)


[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
arr_flatten = arr.flatten()
print(arr_flatten)
print(arr_flatten.shape)

print(arr)
print(arr.shape)

[1 2 3 4 5 6]
(6,)
[[1 2 3]
 [4 5 6]]
(2, 3)


In [ ]:
# transposing of arrays -> swaps its rows and columns(axes)
# -> useful for matrix operations and aligning dimensions


# A  B
# m*n   n*k


# A  3*1
# B  4*1  -> B_T -> 1*4

# A*B?
# B*A?

# A* B_T  -> 3 * 4

# m*n and n*k  -> m*k

In [ ]:
arr= np.array([[1,2,3],[4,5,6]])
print(arr)
print(arr.shape)

arr_T = arr.T
print(arr_T)
print(arr_T.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[1 4]
 [2 5]
 [3 6]]
(3, 2)


In [ ]:
# Advanced indexing and slicing in NumPy arrays

# indexing -> process of accessing individual elements or subsets of elements in an array
# numpy supports 1D,2D and 3D indexing depending on the array dimensions

import numpy as np

# 1D array

arr1 = np.array([10,20,30,40])
print(arr1[2])
print(arr1[0])


30
10


In [ ]:
# 2D array
arr2= np.array([[1,2,3],[4,5,6]])

print(arr2[0])

# rows followed by columns

print(arr2[0][1])

[1 2 3]
2


In [ ]:
# 2nd row , 3rd column?

print(arr2[1][2])

6


In [ ]:
print(arr2[1,2])

6


In [ ]:
print(arr2[0,0])

1


In [ ]:
print(arr2[1,])

[4 5 6]


In [ ]:
print(arr2[,0])

SyntaxError: invalid syntax (2679703548.py, line 1)

In [ ]:
# indexing 3D arrays

arr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(arr)

print(arr.ndim)
print(arr.shape)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
3
(2, 2, 2)


In [ ]:
# 1st element in x axes
# 1st element in y axes
# 2nd element in z axes

print(arr)
print(arr[0,0,1])

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
2


In [ ]:
# how do we index number 4 ?
print(arr[0,1,1])

4


In [ ]:
print(arr[1,0,1])

6


In [ ]:
print(arr[1,1,0])

7


In [ ]:
print(arr[0])

[[1 2]
 [3 4]]


In [ ]:
print(arr[0,0])
print(arr[0,0,0])
print(arr[0,0,1])

[1 2]
1
2


In [ ]:
print(arr[0][0])

[1 2]


In [ ]:
# slicing -> extracting subsets of elements from an array using start:stop:step
# default step size is +1

arr= np.array([[1,2,3],[4,5,6]])
arr1=arr.flatten()
print(arr1)
print(arr1.ndim)
print(arr1.shape)

[1 2 3 4 5 6]
1
(6,)


In [ ]:
print(arr1[1:3])

print(arr1[1:3:1])

[2 3]
[2 3]


In [ ]:
# how to access all the elements?
#  we want start at 0 and go till end
print(arr1[0:])

[1 2 3 4 5 6]


In [ ]:
# lets say we want to access all the even indexed numbers (indexing start at 0)
print(arr1[0::2])

# start:stop:step

[1 3 5]


In [ ]:
# odd indexed numbers?
print(arr1[1::2])

[2 4 6]


In [ ]:
# I want to print the first 3 numbers that are there..

print(arr1[0:3])
print(arr1[:3])

[1 2 3]
[1 2 3]


In [ ]:
# lets say we want to print complete array
print(arr1)
print(arr1[:])

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
# lets say we want to print all the elements in reverse order.. how do we do?

print(arr1[5::-1])

[6 5 4 3 2 1]


In [ ]:
# how to get first 3 elements in reverse order?
print(arr1[2::-1])

[3 2 1]
