In [ ]:
# Array  Manipulations and Linear algebra operations

import numpy as np
a=np.array([1,2,3])
b=np.array([4,5,6])

print(a,b)

[1 2 3] [4 5 6]


In [ ]:
# stacking of arrays

# stacking is used to combine arrays together either row-wise (vstack)  or column-wise(hstack)

print(np.vstack((a,b)))

[[1 2 3]
 [4 5 6]]


In [ ]:
print(np.hstack((a,b)))

[1 2 3 4 5 6]


In [ ]:
# splitting arrays -> splitting divides an array into multiple-sub arrays using np.split(), np.hsplit(),np.vsplit()

arr= np.array(([1,2,3,4],[5,6,7,8]))

print(arr)
print(np.hsplit(arr,2))

[[1 2 3 4]
 [5 6 7 8]]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [ ]:
print(np.vsplit(arr,2))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]


In [ ]:
# vstack and vsplit are opposite to each other
# hstack and hsplit are opposite to each other

In [ ]:
print(np.split(arr,2,axis=0))  #axis=0 means vsplit
# axis=1 means hsplit .. if we dont pass any axis argument.. by default split will be happening

print(np.split(arr,2,axis=1))

[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]


In [ ]:
# inserting -> is it used to insert values along a given axis in an array

# np.insert(arr,index,value)

arr=np.array([1,2,3,5])   #now lets say we want to insert number 10 at index 3
# inserting is not replacing..inserting is adding an element to existing data structure

new_arr = np.insert(arr,3,10)
print(new_arr)


[ 1  2  3 10  5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])

# 1 2 3
# 4 5 6

new_arr=np.insert(arr,3,[7,8],axis=1)   #axis=1 -> adds a additional column
print(new_arr)

[[1 2 3 7]
 [4 5 6 8]]


In [ ]:
# inserting an additional row
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
new_arr = np.insert(arr,2,[7,8,9],axis=0)
print(new_arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [ ]:
# deletion

arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
new_arr= np.delete(arr,2)  #deletes the element at index 2
print(new_arr)

[1 2 4 5]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
# delete(arr,index,axis) -> deletes at specified index .. axis=0 means rows .. axis=1 means columns
new_arr=np.delete(arr,2,axis=1)
print(new_arr)

[[1 2]
 [4 5]]


In [ ]:
new_arr=np.delete(arr,1,axis=0)
print(new_arr)

[[1 2 3]]


In [ ]:
# append() -> inserts elements at the end of the array

arr=np.array([1,2,3])
new_arr=np.append(arr,[4,5,6])
print(new_arr)

[1 2 3 4 5 6]


In [ ]:
# nditer() -> provides flexible iteration over arrays,supporting different memory layouts and order

arr=np.array([[1,2],[3,4]])
print(arr)

[[1 2]
 [3 4]]


In [ ]:
#  C order -> one row after the other

for x in np.nditer(arr,order='C'):
  print(x, end=' ')

1 2 3 4 

In [ ]:
# F order -> Fortran order -> one column after the other
for x in np.nditer(arr,order='F'):
  print(x, end=' ')

1 3 2 4 

In [ ]:
# linear algebra in numpy

# dot product
a=np.array([1,2])
b=np.array([3,4])

# a= a1 i + b1 j
# b= a2 i + b2 j
# np.dot(a,b) = a1*a2 + b1*b2

print(np.dot(a,b))

# 1*3  + 2*4

11


In [ ]:
arr=np.array([[1,2],[3,4]])

print(arr.T)

[[1 3]
 [2 4]]


In [ ]:
# determinant , inverse , adjoint , identity

print(np.linalg.det(arr))

-2.0000000000000004


In [ ]:
print(np.linalg.inv(arr))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [ ]:
# eigen values and eigen vectors

vals, vecs = np.linalg.eig(arr)
print(vals)
print(vecs)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [ ]:
# 2x + y =8
# x+3y =13

# [2 1] =[8]
# [1 3] =[13]

A = np.array([[2,1],[1,3]])
# print(A)
b = np.array([8,13])

x=np.linalg.solve(A,b)
print(x)


# 2*2.2 + 1*3.6 =8
# 2.2 + 3*3.6 =13

[2.2 3.6]


In [ ]:
# random sampling and synthetic data generation

# np.random() -> that allows us to generate random numbers for simulations , ML datasets and testing

# 1) np.random.rand() -> generates random number in the range of [0,1) with a uniform distribution

import numpy as np
arr=np.random.rand(2,3)  #input passed.. represents shape of the required array
print(arr)

[[0.74692077 0.91803049 0.70120498]
 [0.54622318 0.54713033 0.98321999]]


In [ ]:
# 2) np.random.randn() -> generates random numbers from a standard normal distribution of mean=0 and SD=1
arr=np.random.randn(2,3)
print(arr)

[[-0.78013137 -0.39062033  0.51045009]
 [ 0.09560249  0.57047662  0.34060113]]


In [ ]:
# 3) np.random.randint() -> random integers with in a given range

arr=np.random.randint(1,10,(3,3))
print(arr)

[[4 9 8]
 [1 6 1]
 [1 8 4]]


In [ ]:
# shuffling of arrays -> np.random.shuffle() -> randomnly shuffle elements inside the array

print(arr)

[[4 9 8]
 [1 6 1]
 [1 8 4]]


In [ ]:
np.random.shuffle(arr)
print(arr)

[[1 8 4]
 [4 9 8]
 [1 6 1]]


In [ ]:
arr=np.array([1,2,3,4])
np.random.shuffle(arr)
print(arr)

[2 3 1 4]


In [ ]:
arr=np.array([[1,2,5],[3,4,6]])
np.random.shuffle(arr)
print(arr)

[[3 4 6]
 [1 2 5]]


In [ ]:
# shuffling a 2D array.. rows will be shuffled..but elements inside the row will not shuffled

# 2D array -> flatten -> shuffle -> break it into parts again

In [ ]:
arr=np.array([[1,2,5],[3,4,6]])
flat=arr.flatten()
np.random.shuffle(flat)
new_arr=flat.reshape(arr.shape)
print(new_arr)

[[4 2 1]
 [3 5 6]]


In [ ]:
# seeding ?

In [ ]:
# identity and diagonal matrices

print(np.identity(3))
print(np.diag([1,2,3]))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [ ]:
p1 =np.array([1,2])
p2=np.array([3,4])

dist= np.linalg.norm(p1-p2)
print(dist)

2.8284271247461903


In [ ]:
# random -> helpful for generating ML datasets

# 100 samples and 3 features
X =np.random.rand(100,3)
# print(X)

y=np.random.randint(0,100,10)
print(y)


[50  2 67 20 42 57  7 29  2 77]


In [ ]:
# seeding?

np.random.seed(32)

In [ ]:
np.random.seed(32)
y=np.random.randint(0,100,10)
print(y)

[87 43  5 54 62 88 19 71 89  3]
