In [ ]:
import numpy as np
import time
import sys

size=100000

python_list = range(size)
numpy_array = np.arange(size)



In [ ]:
print("Performance comparision between Numpy Arrays and Python Lists")

print("Element wise addition( adding 5 to each element)")

start = time.time()
result_list = [x+5 for x in python_list]
end=time.time()
list_time = end-start

start = time.time()
result_array = numpy_array + 5
end = time.time()
numpy_time = end - start

print(list_time)
print(numpy_time)

Performance comparision between Numpy Arrays and Python Lists
Element wise addition( adding 5 to each element)
0.02282547950744629
0.00047707557678222656


In [ ]:

print("Element wise multiplication( multiplying 5 to each element)")

start = time.time()
result_list = [x*5 for x in python_list]
end=time.time()
list_time = end-start

start = time.time()
result_array = numpy_array * 5
end = time.time()
numpy_time = end - start

print(list_time)
print(numpy_time)

Element wise multiplication( multiplying 5 to each element)
0.007119178771972656
0.0008068084716796875


In [ ]:
for i in range(1,11):
  print(i)

1
2
3
4
5
6
7
8
9
10


In [ ]:
np.arange() -> create numpy arrays  with evenly spaced values with in a given interval

# np.arange(start,stop,step)
start -> first value to include
stop -> value to stop before ( stop is NOT included)
step -> gap between consecutive values



In [ ]:
import numpy  as np
arr = np.arange(1,10,2)

print(arr)

[1 3 5 7 9]


In [ ]:
# eye(n) -> creates a 2D identity-like matrix of size nxn, with 1s on the diagonal and 0s elsewhere

eye_mat = np.eye(3) #-> creates a 3x3 identity matrix
print(eye_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.identity(n) -> creates a 2D identity matrix of nxn dimensions

identity_mat = np.identity(3)
print(identity_mat)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
# np.zeros(shape) -> creates an array filled with zeros, given the desired shape

import numpy as np
zeros_array = np.zeros((3,5))
print(zeros_array)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [ ]:
# np.ones(shape) -> creates and array filled with ones, given the desired shape

ones_array=np.ones((3,5))
print(ones_array)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
creating a ndarray in numpy:

ndarray -> the core data structure in numpy -> representing multidimensional arrays of homogeneous data types

In [ ]:
-> we can create using lists/tuples using np.array() or by using some creators like arange(), ones(),zeros(),eye()

In [ ]:
# from a python list

arr = np.array([1,2,3,4,5])
print(arr)


[1 2 3 4 5]


In [ ]:
# np.linspace : number-based
arr_linspace = np.linspace(0,1,11) #exactly picks 11 points between 0 and 1(both inclusive)

print(arr_linspace)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
arr_arange = np.arange(0,1.1,0.1)
print(arr_arange)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]


In [ ]:
# name,age,gpa,graduated

student_dtype = np.dtype([
    ('name','U20'), #unicode string with 20 maximum chars
    ('age','i4'), #32-bit integer
    ('gpa','f8'),  #64 bit -floating point number
    ('graduated','?') #boolean
])

# name,age,gpa,graduated
# Eswar, 30,8.8,yes
# Sai, 20,yes, 9.8


In [ ]:
# lets create structured data using dtype
students = np.array([
    ('Dinesh',25,9.1,True),
    ('Pavan',30, 9.3, True),
    ('Usha',26,8.9,True),
    ('Jagadeesh',19,9.4,False)
])

In [ ]:
students_1 = np.array([
    ('Dinesh',25,9.1,True),
    ('Pavan',30, 9.3, True),
    ('Usha',26,8.9,True),
    (19,'Jagadeesh',9.5,True)
    # ('Jagadeesh',19,False,9.5)
],dtype=student_dtype)

print(students_1)
# ('Jagadeesh',19,False,9.5)

ValueError: invalid literal for int() with base 10: 'Jagadeesh'

In [ ]:
print(students_1)

[('Dinesh', 25, 9.1,  True) ('Pavan', 30, 9.3,  True)
 ('Usha', 26, 8.9,  True) ('Jagadeesh', 19, 0. ,  True)]


In [ ]:
students = np.array([
    ('Dinesh',25,9.1,True),
    ('Pavan',30, 9.3, True),
    ('Usha',26,8.9,True),
    ('Jagadeesh',19,9.4,False)
],dtype=student_dtype)