In [ ]:
import numpy as np
arr2=np.array([[1,2,3],[4,5,6]])

print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr2[1,1])

5


In [ ]:
# lets say we want all rows of second column .. (numbering starts at 0)
print(arr2[0,2])
print(arr2[1,2])

3
6


In [ ]:
print(arr2[:,2])

[3 6]


In [ ]:
# 0th and 1st columns of all the rows
# print(arr2[:,0])
# print(arr2[:,1])

print(arr2[:,0:2])

[[1 2]
 [4 5]]


In [ ]:
print(arr2[:,0:2])

[[1 2]
 [4 5]]


In [ ]:
print(arr2[,1])

SyntaxError: invalid syntax (1968989332.py, line 1)

In [ ]:
print(arr2[1,:])

[4 5 6]


In [ ]:
arr3 = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])


# print all the elements of 0th index of third dimension

print(arr3[:,:,0])
# 00,01,10,11
# print(arr3[0,0,0])
# print(arr3[0,1,0])
# print(arr3[1,0,0])
# print(arr3[1,1,0])
print(arr3[:,:,0])

[[1 3]
 [5 7]]


In [ ]:
print(arr3[0])  # 0th index of first dimension

[[1 2]
 [3 4]]


In [ ]:
print(arr3[1])

[[5 6]
 [7 8]]


In [ ]:
print(arr3[0][0])
print(arr3[0][1])

[1 2]
[3 4]


In [ ]:
print(arr3[0,0])
print(arr3[0,1])

[1 2]
[3 4]


In [ ]:
print(arr3[0,0,0])
print(arr3[0,1,0])

1
3


In [ ]:
print(arr3[0])
print(arr3[0][0])
print(arr3[0][0][0])


[[1 2]
 [3 4]]
[1 2]
1


In [ ]:
print(arr3[0])
print(arr3[0,0])
print(arr3[0,0,0])


[[1 2]
 [3 4]]
[1 2]
1


In [ ]:
arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0,:])

[1 2 3]


In [ ]:
print(arr2[0,0:2])

[1 2]


In [ ]:
print(arr2[0,0:3])

[1 2 3]


In [ ]:
print(arr2[0,0:3:2])

[1 3]


In [ ]:
# 3 2 1

print(arr2[0,:])
print(arr2[0,::-1])



[1 2 3]
[3 2 1]


In [ ]:
# Fancy indexing -> uses a list or array of indices to access multiple elements simultaneously

arr1=np.array([10,20,30,40])

print(arr1)

[10 20 30 40]


In [ ]:
# access 10,30,40

print(arr1[0])
print(arr1[2])
print(arr1[3])

10
30
40


In [ ]:
print(arr1[[0,2,3]])

[10 30 40]


In [ ]:
# boolean indexing -> allows selection of elements based on a condition that returns True/False

print(arr1)

[10 20 30 40]


In [ ]:
# lets say we want to see the values which are greater than 20

print(arr1[arr1>20])
# [10 20 30 40]
# print(arr1[40>20])
# print(arr1[True])

[30 40]


In [ ]:
print(arr1[arr1>10])

[20 30 40]


In [ ]:
print(arr1[(arr1>10) & (arr1<30)])   # | -> or

# T | T -> T
# T | F -> T
# F | T -> T
# F | F -> F
# T & T -> T
# T & F -> F
# F & T -> F
# F & F -> F

[20]


In [ ]:
print(arr1[(arr1%3)==0])

[30]


In [ ]:
# Arithmetic Operations

# -> numpy supports element wise arithmetic operations between arrays of same shape or compatible shapes

a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)




[5 7 9]


In [ ]:
print(a*b)

[ 4 10 18]


In [ ]:
# broadcasting rules  -> allows arithmetic operations on arrays of different shapes by automatically
# expanding the smaller array

a=np.array([[1,2,3],[4,5,6]])
print(a)

print(a+10)

[[1 2 3]
 [4 5 6]]
[[11 12 13]
 [14 15 16]]


In [ ]:
# aggregate functions

print(a)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(a.sum()) #returns sum of all the elements

21


In [ ]:
print(a.mean())

3.5


In [ ]:
# axis=0 -> sums up along columns
# axis=1 -> sums up along rows

print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))

[[1 2 3]
 [4 5 6]]
[5 7 9]
[ 6 15]


In [ ]:
print(a.mean(axis=0))
print(a.mean(axis=1))

[2.5 3.5 4.5]
[2. 5.]


In [ ]:
print(a.max())

6


In [ ]:
print(a.min())

1


In [ ]:
print(a.max(axis=0))
print(a.max(axis=1))

[4 5 6]
[3 6]


In [ ]:
print(a.min(axis=0))
print(a.min(axis=1))

[1 2 3]
[1 4]


In [ ]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
print(arr[0])

[1 2 3]


In [ ]:
print(arr[0,:])

[1 2 3]


In [ ]:
print(arr[0,0])
print(arr[0,1])
print(arr[0,2])

1
2
3


In [ ]:
print(arr[0,0:3])  #0,1,2

# start:stop:step .. we start at start and we end before stop..default step size is +1

[1 2 3]


In [ ]:
print(arr[0,0:3:1])  #0,1,2


[1 2 3]


In [ ]:
print(arr[0,0:3:2])  #0,1,2


[1 3]
